// flow-typed signature: d692ecc81fc7d078cc86b43e2e150c2b
// flow-typed version: <<STUB>>/@pact-foundation/pact_v^9.2.2/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pact-foundation/pact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pact-foundation/pact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pact-foundation/pact/common/logger' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/common/metadata' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/common/net' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/common/net.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/common/request' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/common/request.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/common/utils' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/apolloGraphql' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/apolloGraphql.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/graphql' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/graphql.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/interaction' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/interaction.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/matchers' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/matchers.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/message' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/mockService' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/mockService.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/options' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/verifier' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/dsl/verifier.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/errors/configurationError' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/errors/graphQLQueryError' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/errors/matcherError' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/errors/verificationError' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/httpPact' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/httpPact.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/messageConsumerPact' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/messageConsumerPact.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/messageProviderPact' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/messageProviderPact.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/pact-web' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/pact-web.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/pact.integration.spec' {
  declare module.exports: any;
}

declare module '@pact-foundation/pact/pact' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pact-foundation/pact/common/logger.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/common/logger'>;
}
declare module '@pact-foundation/pact/common/metadata.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/common/metadata'>;
}
declare module '@pact-foundation/pact/common/net.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/common/net'>;
}
declare module '@pact-foundation/pact/common/net.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/common/net.spec'>;
}
declare module '@pact-foundation/pact/common/request.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/common/request'>;
}
declare module '@pact-foundation/pact/common/request.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/common/request.spec'>;
}
declare module '@pact-foundation/pact/common/utils.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/common/utils'>;
}
declare module '@pact-foundation/pact/dsl/apolloGraphql.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/apolloGraphql'>;
}
declare module '@pact-foundation/pact/dsl/apolloGraphql.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/apolloGraphql.spec'>;
}
declare module '@pact-foundation/pact/dsl/graphql.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/graphql'>;
}
declare module '@pact-foundation/pact/dsl/graphql.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/graphql.spec'>;
}
declare module '@pact-foundation/pact/dsl/interaction.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/interaction'>;
}
declare module '@pact-foundation/pact/dsl/interaction.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/interaction.spec'>;
}
declare module '@pact-foundation/pact/dsl/matchers.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/matchers'>;
}
declare module '@pact-foundation/pact/dsl/matchers.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/matchers.spec'>;
}
declare module '@pact-foundation/pact/dsl/message.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/message'>;
}
declare module '@pact-foundation/pact/dsl/mockService.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/mockService'>;
}
declare module '@pact-foundation/pact/dsl/mockService.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/mockService.spec'>;
}
declare module '@pact-foundation/pact/dsl/options.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/options'>;
}
declare module '@pact-foundation/pact/dsl/verifier.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/verifier'>;
}
declare module '@pact-foundation/pact/dsl/verifier.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/dsl/verifier.spec'>;
}
declare module '@pact-foundation/pact/errors/configurationError.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/errors/configurationError'>;
}
declare module '@pact-foundation/pact/errors/graphQLQueryError.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/errors/graphQLQueryError'>;
}
declare module '@pact-foundation/pact/errors/matcherError.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/errors/matcherError'>;
}
declare module '@pact-foundation/pact/errors/verificationError.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/errors/verificationError'>;
}
declare module '@pact-foundation/pact/httpPact.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/httpPact'>;
}
declare module '@pact-foundation/pact/httpPact.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/httpPact.spec'>;
}
declare module '@pact-foundation/pact/messageConsumerPact.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/messageConsumerPact'>;
}
declare module '@pact-foundation/pact/messageConsumerPact.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/messageConsumerPact.spec'>;
}
declare module '@pact-foundation/pact/messageProviderPact.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/messageProviderPact'>;
}
declare module '@pact-foundation/pact/messageProviderPact.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/messageProviderPact.spec'>;
}
declare module '@pact-foundation/pact/pact-web.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/pact-web'>;
}
declare module '@pact-foundation/pact/pact-web.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/pact-web.spec'>;
}
declare module '@pact-foundation/pact/pact.integration.spec.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/pact.integration.spec'>;
}
declare module '@pact-foundation/pact/pact.js' {
  declare module.exports: $Exports<'@pact-foundation/pact/pact'>;
}
