// flow-typed signature: 3eb055aae0d9135ee8bec8adcae48309
// flow-typed version: <<STUB>>/webpack-serve-waitpage_v1.0.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-serve-waitpage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-serve-waitpage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-serve-waitpage/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-serve-waitpage/lib/index.js' {
  declare module.exports: $Exports<'webpack-serve-waitpage/lib/index'>;
}
